# Generated by Django 5.2.4 on 2025-08-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycmodel',
            name='client_no',
            field=models.CharField(default=0, max_length=50, verbose_name='Client Number'),
        ),
    ]
