# Generated by Django 5.2.4 on 2025-08-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycmodel_client_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycmodel',
            name='client_no',
        ),
    ]
