# Generated by Django 5.2.4 on 2025-08-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_remove_kycmodel_client_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycmodel',
            name='risk_category',
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
