# Generated by Django 5.2.4 on 2025-08-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_remove_kycmodel_risk_category_alter_kycmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='income_amount',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
