# Generated by Django 5.2.4 on 2025-08-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_alter_kycmodel_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='ward_no',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
