# Generated by Django 5.2.4 on 2025-08-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_alter_kycmodel_ward_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='house_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
