# Generated by Django 5.2.4 on 2025-08-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_alter_kycmodel_house_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='profession',
            field=models.CharField(blank=True, choices=[('Service', 'Service'), ('Business', 'Business'), ('Other', 'Other')], default='Service', max_length=50, null=True),
        ),
    ]
