# Generated by Django 5.2.4 on 2025-08-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0008_alter_kycmodel_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='date_of_birth_ad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
