# Generated by Django 5.2.4 on 2025-08-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_alter_kycmodel_date_of_birth_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycmodel',
            name='document_number',
            field=models.CharField(max_length=20, verbose_name='Document Number'),
        ),
    ]
